include: config/model/ad_base.yaml

model: AD

# Transformer
tf_n_embd: 64
tf_n_layer: 4
tf_n_head: 8
tf_dropout: 0.1
tf_attn_dropout: 0.1
tf_n_inner: 256
n_transit: 1000

# training
lr: 0.01
train_batch_size: 512
test_batch_size: 2048
train_source_timesteps: 10000
test_source_timesteps: 2000
train_timesteps: 50000
num_warmup_steps: 0
learn_var: True

train_n_stream: 100

num_workers: 2
