alg: PPO
alg_seed: 0
batch_size: 200
dim_actions: 4
dim_obs: 11
env: metaworld
horizon: 100
max_reward: 1000
mw_seed: 0
n_epochs: 20
n_process: 8
n_steps: 100
n_stream: 100
policy: MlpPolicy
source_lr: 0.0003
task: pick-place-v2
total_source_timesteps: 1000000
